### ISSUE TITLE
Can't override static admin functions

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#167]
You can't override a static admin function when using a custom admin class (::drawField, for example)

**Comment by timbuckingham** [comment]
Static methods should currently be overrideable, but right now they're being called improperly in other methods (currently using self::, should be using static::). Will fix!

**Comment by benplum** [comment]
This issue is that all form drawing code calls BigTreeAdmin::drawField directly. The custom class is ignored.

**Comment by timbuckingham** [comment]
Oh, I see! Ok, will look into that more... hm.

**Comment by timbuckingham** [comment]
Proposed solution:
- What were previously the BigTreeCMS and BigTreeAdmin classes are now BigTreeCMSBase and BigTreeAdminBase
- When you define a custom base or admin class, instead of creating an instance of that class as $cms or $admin we do: "BigTreeCMS extends YourCustomClass {}" or "BigTreeAdmin extendsion YourCustomClass {}".
- If you don't define custom ones, we just do "BigTreeCMS extends BigTreeCMSBase {}".
- Then we just do $cms = new BigTreeCMS and $admin = new BigTreeAdmin.

Thoughts?

**Comment by benplum** [comment]
If BigTreeCMS extends CustomCMS wouldn't my custom function overrides be overridden?

**Comment by timbuckingham** [comment]
BigTreeCMS is just an empty class -- it inherits everything you defined in your CustomCMS class. Just need a consistent name to reference calls by so we create BigTreeCMS.

**Comment by benplum** [comment]
Wouldn't a variable be easier? http://stackoverflow.com/a/3121559/2612062

**Comment by timbuckingham** [comment]
I switched to using static methods so we wouldn't have to constantly globalize $cms and $admin (it got tricky in calls to _destruct, we would sometimes have $admin destructing before $cms and vice versa). It would also be another global variable that could potentially be overwritten.
