### ISSUE TITLE
.htaccess Issues uploading to server 

### ISSUE THREAD

**Issue by christianldm** [bigtreecms/BigTree-CMS#168]
Using route advance and upload to the web server and for some reasons the site.css and site.js are not found
therefore site doesnt display properly and I get a Internal Server Error when trying to navigate to another page and I can see the .htaccess and mod_rewrite is supported by the host
is there any suggestions for this problem no idea what's wrong

**Comment by timbuckingham** [comment]
A lot of shared servers don't support the compression and expiration directives in the Advanced .htaccess. Does using Simple Rewrite Routing work properly for you?

**Comment by christianldm** [comment]
i tried to upload it with Simple Rewrite and but still giving me same error as before it says that the installation complete but with no css and js
on my local server works just fine with advance route
Im going to install it with basic

**Comment by timbuckingham** [comment]
It's possible that while your server supports .htaccess the rules have to be defined in a specific directory. I've seen that with a few hosts.

**Comment by christianldm** [comment]
thank's for the help I managed to uploaded with advance route and works fine , may be was something with the server.
Also I'm creating this site and they want to do an events calendar that they can manage from bigtree similar to form builder package. Is there any package of way to do this? 
I'd really appreciate 
thanks

**Comment by timbuckingham** [comment]
You can find an events package for 4.1 currently at:
http://www.timbuckingham.com/events.zip

It provides an admin interface for entering events (including recurring events) and a class with a bunch of calls for querying for events. There's no front end interface, so that has to be built out by hand.

**Comment by christianldm** [comment]
Great it really looks what I'm after just the front end display has to be built by template I guess just wondering how would that be? Same as the form builder right 
thank's for the package

**Comment by timbuckingham** [comment]
You can call methods like BTXEvents::getUpcomingEvents(10) to retrieve the next 10 events and draw them however you want.

Form Builder comes with a front end that you just need to style since it's not a very flexible system (and without the template would be really difficult to implement). The Events module is super flexible so we don't have a set of pre-built templates for it.

**Comment by christianldm** [comment]
ok thank's for that advise I'm on it let know how's it going
