### ISSUE TITLE
issue on  installing on subfolder domain 

### ISSUE THREAD

**Issue by christianldm** [bigtreecms/BigTree-CMS#182]
I'm trying to install bigtree again on a different subdomain eg: http://134.0.17.78/~nouvague/ and after installed it's missing main.css and giving 404 not found error. Is this because it's on a subfolder?
As I have installed other bigtree on a different domain eg: http://qcross.likedigitalmedia.com/ and it works just fine as this domain is not on a subfolder

**Comment by timbuckingham** [comment]
Being on a sub folder shouldn't be an issue, as long as .htaccess tells the folder to look inside /site/ for index.php as it normally would. We always use subfolders for development projects, so it's not an issue inherent to that.

**Comment by christianldm** [comment]
ok it works now but the admin link it's not working I used htaccess route and the url show the front end without long in http://134.0.17.78/~nouvague/site/index.php/admin/ any ideas?

**Comment by christianldm** [comment]
on my environment.php I have 
$bigtree["config"]["admin_root"] = "http://134.0.17.78/~nouvague/admin/"; as url to the admin but still not luck

**Comment by timbuckingham** [comment]
If you're seeing /index.php/ in your URLs it's because BigTree is using "basic" routing in /custom/environment.php. If your server supports .htaccess and mod_rewrite directives (and you have the .htaccess files in the root directory and /site/) you can switch to $bigtree["config"]["routing"] = "htaccess".

If your server doesn't support htaccess you'll want to switch $bigtree["config"]["admin_root"] to "http://134.0.17.78/~nouvague/site/index.php/admin/"

**Comment by christianldm** [comment]
yeah that did the trick to log in but I'd like the url cleaner but I guess my host doesn't support htaccess  but that will do for now
