### ISSUE TITLE
Group Callouts in Modal Dropdown

### ISSUE THREAD

**Issue by mdewyer** [bigtreecms/BigTree-CMS#188]
It's really nice to be able to group callouts, but it would be helpful if the grouping was reflected in the "Callout Type" dropdown when adding / editing a callout item. An easy way to achieve this would be using the optgroup tag. 

Also, consider if reflecting the order of callouts within a group would be a good UX change or not (so instead of ordering them alphabetically in the dropdown, if making them follow the same order that they've been organized through the developer section makes more sense; if nothing else it adds more flexibility with a very minor query change).

**Comment by timbuckingham** [comment]
I agree that it would be a nice change (in 4.1) to have them inside optgroups when you haven't chosen a specific group. We're going to be pushing 4.1.6 out sometime this week, but I'll try to slot that into 4.1.7 -- it makes total sense. Right now the sort order chosen in the admin should be reflected when a callout field is using a specific group. If the callout field is using all groups it sorts alphabetically (as the sort order is on a per group basis).

Unfortunately (or fortunately, depending on your perspective!) the direction for callout grouping was changed to be more flexible in 4.2. In 4.2 you can assign callouts to multiple groups and multiple groups to each callout field. Since positioning doesn't really make sense when you're pulling multiple groups into a single list, 4.2 does away with the draggability in the admin as well in favor of alphabetical sorting across the board.

**Comment by mdewyer** [comment]
Very cool! Thanks for adding that. And I like what you're doing in 4.2.
Having one standard sorting method will simplify things, and the
flexibility you're adding sounds great! Thanks again!
