### ISSUE TITLE
BigTree doesn't seem to work with HTTPS/SSL?

### ISSUE THREAD

**Issue by peterbrinck** [bigtreecms/BigTree-CMS#207]
Hi

I just installed BigTree, but it doesn't seem like BigTree can work with SSL?
First of, BigTree automatic removes SSL from the site, even though I've set it to ALWASY use SSL
So, it won't load CSS and JS, because it uses SSL, and BigTree tries to loads the CSS and JS from the server without using SSL

**Comment by timbuckingham** [comment]
I believe the install setting is "Force Login over SSL" -- that one only sets it up so that when a user tries to access the login page of the admin it forces that single page over SSL.

To force the whole site over SSL you'll want to edit /custom/environment.php and set your config's domain, www_root, static_root, and admin_root settings to be the https:// URL.

**Comment by peterbrinck** [comment]
I'll try that
