### ISSUE TITLE
Duplicate Photo when Equal to Crop Dimensions

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#212]
I noticed some odd behavior when uploading a photo that matches the dimensions of a defined crop with a blank prefix. I know it should only upload the cropped photo when the prefix is blank but it's uploading both even though the dimensions of the original match the cropped dimensions. I traced the steps and found that when processing the photo there's a check for when the width/height matches the cropped dimensions. At the bottom of that if statement is this call: $storage->store($temp_copy,$crop["prefix"].$pinfo["basename"],$field["options"]["directory"],false) (admin.php line 6228);

If I comment that line out then it only uploads and saves the original which is the desired outcome. I left it commented out and tested with multiple crops (where the extra crops were of different dimensions than the photo) and with no crops and everything appeared to behave as expected. I was wondering if there was some negative implication I could not see to removing that line? My thinking is it should be ok to remove since it is only executed when an uploaded photo matches a crop's dimensions?

**Comment by timbuckingham** [comment]
I think the behavior you're describing is intentional but I may just be confused. Say we have an image upload with the following options:

Crops:
400x300 (4x3_ prefix)
400x400 (square_ prefix)

Thumbnails:
1024x768 (no prefix)

If you uploaded a 400x400 image named image.jpg it should make:
- 4x3_image.jpg (400x300)
- square_image.jpg (400x400)
- image.jpg (400x400)

Even though square_image.jpg and image.jpg are the same, the front end is probably always looking for BigTree::prefixFile($image,"square_") when looking for the square image.

**Comment by jmason03** [comment]
Right I agree with that, but I'm experiencing the duplication when I leave the prefix blank. So my situation is:

Crops:
400 x 400 (no prefix)
400 x 200 (small_ prefix)

No Thumbnails

Saved Files:
image.jpg
image-2.jpg
small_image.jpg

Are you not experiencing that on your setup?

**Comment by timbuckingham** [comment]
Sorry, I guess I was just confused :) I'll do some testing on that and get a fix in place!

**Comment by jmason03** [comment]
Oh no it's not a problem, I definitely could have been clearer on my initial post. Thanks for looking into this!

**Comment by timbuckingham** [comment]
Should be fixed in the above commit. Just had to add a check to make sure a prefix existed (since the original was already uploaded).
