### ISSUE TITLE
Features Added for Many-to-Many

### ISSUE THREAD

**Issue by randyhook** [bigtreecms/BigTree-CMS#218]
So, this isn't an issue, just a feature addition. Do I still post it here?

I've modified the Many-to-Many field to give the user the option of adding a second descriptor column and an override for the Add Item button label.

The second descriptor column comes in handy for scenarios like the following: You have a users table with last_name and first_name columns. You would like the Many-to-Many control to render out Last Name, First Name instead of just, say, Last Name.

The Add Item button label override allows you to replace the default "Add Item" text on the Many-to-Many control. In the above scenario, you could enter "Add User".

Link to branch: https://github.com/MindscapeSolutions/BigTree-CMS/tree/many-to-many

**Comment by timbuckingham** [comment]
First, yeah, feature requests or enhancements can totally be added here!

I'm not sure whether we want this functionality in the core or not mostly because I have the philosophy that less configuration options are better and there's already a way to do two descriptors (though not the easiest to implement). You can use a [filter on the Many to Many field](https://www.bigtreecms.org/docs/dev-guide/field-types/#ManyToMany) and then manually query for the fields you want to use for the descriptor and return them. An example:

function filterManyToMany($list) {
	$new_list = array();
	foreach ($list as $id => $name) {
		$item = sqlfetch(sqlquery("SELECT * FROM whatever_table WHERE id = '$id'"));
		$new_list[$id] = $item["column1"]." ".$item["column2"];
	}
	return $new_list;
}

**Comment by randyhook** [comment]
I think the only thing I don't like about that approach is it looks like you could potentially be making a ton of SQL calls just to populate a drop list.

However, I definitely respect your approach on limiting the amount of configuration options.

**Comment by timbuckingham** [comment]
Yeah, I agree that it's a lot of unneeded SQL calls but from a performance standpoint I don't see it as a huge concern (since it's admin-side and not frequently accessed). Maybe we could add a more general purpose data source function that is run *instead* of the original list query. That function could then do whatever it needs (combining data from multiple tables, multiple columns, whatever).

**Comment by randyhook** [comment]
That sounds like a good idea. I'll explore it further.

As far as a real-world example goes: we just developed a BigTree site with a ton of blog posts. We are using the one-to-many field to allow the user to select several posts from the list of all posts. That list is over 2,000 items long, so those individual SQL calls in the filter function are taking a while.

We just overrode the one-to-many for now so we could run one SQL statement (plus it has a join in it).

**Comment by timbuckingham** [comment]
Usually at around 2,000 items the biggest delay we see is in rendering the custom dropdowns (something that I'd love to make faster but seems to be more of a DOM issue than a JS speed issue).
