### ISSUE TITLE
Feature Request: Maintenance Mode Analytics

### ISSUE THREAD

**Issue by NickStees** [bigtreecms/BigTree-CMS#226]
Not sure if this would be a headache to implement. But when maintenance mode is activated the analytics dashboard does not seem to account for any of that traffic.

**Comment by timbuckingham** [comment]
We can't do this directly in BigTree since we don't actually do any of the Google Analytics logging as it's handled in the front end templates by Javascript but what I can do is add a session variable that contains the originally requested URL that you can use to manually fire a tracking event in Google Analytics in the /templates/basic/_maintenance.php file.

I've added $_SESSION["bigtree_referring_url"] as a variable that can be read in maintenance mode that will give you the original URL that a user requested before ending up on the maintenance page:

https://github.com/bigtreecms/BigTree-CMS/commit/b468a0b1adb86770597cef3b0ae03d8bb3146da2

**Comment by NickStees** [comment]
Thanks, that will be a handy session variable, I could use it to display custom messages on the maintenance page.  

I thought the Google Analytics data was pulled in and stored in MySQL via the cron job? So all the values on /admin/dashboard/vitals-statistics/analytics/ are ajax'ed in via Javascript? 

I think I was just wanting the "Two Week Heads-up" bar graph to include traffic from the maintenance page if its activated. Since our maintenance page was activated that graph looks like it has not updated. But in Google Analytics I can see visitor counts on the maintenance URL. 

![image](https://cloud.githubusercontent.com/assets/2799150/12277122/c91e8d48-b947-11e5-8b5e-f44dbeccaf52.png)

**Comment by timbuckingham** [comment]
The two-week heads up is indeed stored in a cache in MySQL but it's pulled directly from Google in the cron job -- if your maintenance page isn't logging traffic via the Google Analytics JS it's not going to be reported to Google (and hence not pulled down via the API).

**Comment by NickStees** [comment]
The maintenance template has Google Analytics tracking code on it. But I don't believe BigTree saves those maintenance page view values anywhere. Here is a screen shot of my Two Week Display, it ends on the exact day my maintenance page (custom url of /openingsoon/ ) went up, and you can see Analytics then started recording from that date as well. 

![image](https://cloud.githubusercontent.com/assets/2799150/12277681/a9eecbe2-b94a-11e5-9465-7dad81f20441.png)

**Comment by timbuckingham** [comment]
From the looks of your heads up panel there it looks like the analytics connection has bugged out (sometimes it's due to a change of the Google Account's password invalidating the token) -- even if Google Analytics failed to track pages it should show new dates in the heads up with 0 counts. I would try disconnecting it and reconnecting and checking to see if that fixes it.

We probably need better error handling on the analytics connection -- maybe something we can add in 4.3 that shows an error pane for Developer level users on the dashboard when a connection has gone awry.

**Comment by NickStees** [comment]
Awe! You are correct that was it, it just needed to be re-connected. 
![image](https://cloud.githubusercontent.com/assets/2799150/12278044/c8e7ddf2-b94c-11e5-8677-d2a4bb3a5933.png)
