### ISSUE TITLE
Remove keywords from SEO

### ISSUE THREAD

**Issue by jawittdesigns** [bigtreecms/BigTree-CMS#227]
I'm actually kind of baffled why it's even there in this day and age. Google hasn't used them at all for years now, and YaBing (Yahoo and Bing) rank them so low in priority that they are pretty much meaningless. 

There's also the risk of someone, who doesn't know what their doing, spamming keywords and getting their site banned from search results. 

It just doesn't seem worth it to have a keyword field at.

**Comment by timbuckingham** [comment]
Definitely a relic of the past when clients refused to believe that keywords didn't matter. There's no risk of keyword spam getting banned since Google/Bing don't even read the field (and the developer has to explicitly draw the keywords field -- nothing is included by default) but I'm going to mark this for removal in 4.3 -- there's no need for it to exist and it's just confusing to the less educated!
