### ISSUE TITLE
Could not connect to MySQL server.

### ISSUE THREAD

**Issue by WeboGraph** [bigtreecms/BigTree-CMS#241]
Why this error on a new xampp installation and all other systems like WordPress run.

**Comment by timbuckingham** [comment]
Can you post a screenshot of where you're receiving the error? Thanks!

**Comment by WeboGraph** [comment]
Database exists and login credentials are ok.

![mysql_error](https://cloud.githubusercontent.com/assets/1372793/14036399/b8eeecea-f238-11e5-923f-1cfa1fceddbe.png)

**Comment by timbuckingham** [comment]
Can you try entering 127.0.0.1 for the Hostname? Some PHP/MySQL installs for some reason act strangely. If that fixes it I'll make sure the BigTree installer does a second attempt using the IP address if the user enters localhost and it fails.

Thanks!

**Comment by WeboGraph** [comment]
The same result! 
 > Could not connect to MySQL server.

**Comment by timbuckingham** [comment]
What kind of LAMP stack are you running? It looks like it might be XAMPP on Windows from the screenshot but I'm not 100% sure. Thanks!

**Comment by WeboGraph** [comment]
XAMPP 5.6.19

**Comment by timbuckingham** [comment]
Thanks -- I'll try to get a Windows environment spun up and see if I can track down the issue.

**Comment by timbuckingham** [comment]
I've found the cause -- it looks like XAMPP on Windows won't properly infer the MySQL port when it's not entered. If you click the "Connect via Socket or Alternate Port" checkbox and enter 3306 for the port it should install properly.

I'm going to update the installer so that it defaults to an explicit port 3306 if none is enter -- thank you for sticking with me in diagnosing this bug!
