### ISSUE TITLE
Edits Not Saving - File Size Upload Error

### ISSUE THREAD

**Issue by saraday** [bigtreecms/BigTree-CMS#246]
We're seeing issues when trying to make edits to pages. When hitting "Save & Preview" or "Save & Publish" we are bumped back to the BigTree Dashboard and the edits do not save. When going back into the page in the CMS, we get this error message:

The file(s) uploaded exceeded the web server’s maximum upload size. If you uploaded multiple files, try uploading one at a time.

(We are not uploading any files.)

We have to go through this process 2-3 before the edits stick.

**Comment by timbuckingham** [comment]
That message is supposed to show when your $_POST data exceeds your server's post_max_size or upload_max_filesize rules. When that happens PHP rejects absolutely all the data you sent over (file or not) and we're left with an empty $_POST array. We show that error rather than just failing to try to give some kind of context.

I would check the Site Status section in Developer to see what it currently sees under the Server Parameters for "Allow 4MB Uploads". If it's showing a red error then there's probably a very low setting in place that's preventing data from posting.

**Comment by timbuckingham** [comment]
Closing this dormant issue, let me know if you're still having trouble!
