### ISSUE TITLE
FastCGI + suPHP issues with php_flag

### ISSUE THREAD

**Issue by matthisamoto** [bigtreecms/BigTree-CMS#260]
I ran into some issues on a server funning FastCGI + suPHP where it wasn't happy about the use of the `php_flag` in the .htaccess file inside of the site directory.

```
php_flag short_open_tag On
php_flag magic_quotes_gpc Off
```

Any chance of placing these declarations into a localized php.ini file or something to get around these limitations or would that cause problems elsewhere? Or maybe just document it in a FAQ on the site with a potential solution?

**Comment by timbuckingham** [comment]
Removing this in the 4.3 branch of BigTree since it uses all full <?php tags and if your host still has magic quotes on the world is a scary place :)

For 4.2 there's still the "Simple Rewrite" install that ditches the php_flags in your htaccess (though you also don't get the gzip compression stuff).
