### ISSUE TITLE
Recommended BigTreeFlickrAPI enhancements

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#262]
Addition of getAlbumPhotos(), getNextPrev(), getAlbums()

Patch file:
[flickr.php.zip](https://github.com/bigtreecms/BigTree-CMS/files/560753/flickr.php.zip)

**Comment by timbuckingham** [comment]
I've added getAlbumPhotos and getAlbums to the Flickr class and added a BigTreeFlickrAlbum class to work with them. They're a little more like the existing methods rather than returning the raw data.

https://github.com/bigtreecms/BigTree-CMS/commit/057efd6ef2bcbc79693926c393f2dd13ba59310e

I didn't add getNextPrev as BigTreeFlickrPhoto already has the getContext method and it seemed a little redundant and the method name wasn't all that clear.

Thanks for the suggestion!
