### ISSUE TITLE
Image upload fields in callouts are not re-processed when callout type is changed

### ISSUE THREAD

**Issue by jemaleddin** [bigtreecms/BigTree-CMS#334]
If a callout is created that has an image upload field and the page is saved, when you come back to edit the callout you can change the callout type. It's nice that it preserves the data from the last callout so you can easily switch between similar callout types, but images that need crops or thumbnails will not be processed in this scenario, leading to missing images.

**Comment by timbuckingham** [comment]
Hopefully this is fixed in 4.3.3 -- BigTree will now try to determine whether the source content is able to be translated over to the new template or callout. If the source image is big enough it will force re-crops if it has a different crop set (or use the existing crop set if it is exactly the same).

This fix should also prevent other resources that would have issues from passing over bad data.
