### ISSUE TITLE
Page > Properties > External Link: Typing causes a loss of input focus

### ISSUE THREAD

**Issue by cyokum** [bigtreecms/BigTree-CMS#337]
When typing in an external link, the input field loses focus after you begin typing. You have to re-enter the input field to continue typing. On first glance, it looks like the disable Template is taking the focus from the external link.

**Comment by timbuckingham** [comment]
I tested this a bunch and could only replicate it in Safari. It seems like the keyup event in Safari is having a lot of trouble with missed keystrokes making it seem like the field loses focus and then regains it.

I've switched this to a background timer checking the value of the external link field instead of checking it on keyup and it seems to have resolved the issue in Safari in the 4.3-devel branch.
