### ISSUE TITLE
When setting an external link all resources get wiped out

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#339]
We've noticed that when you set an external link on a page in BigTree it wipes out all of the content in bigtree_pages for the following fields:
- resources
- template

This means if you ever need to remove the external redirect you have to either rebuild the page or as an administrator using the audit trail revert a view.  It would be much better to preserve the content and if the external link was removed all of the content would remain.

We're running version 4.2.22.

**Comment by timbuckingham** [comment]
The challenge with changing this behavior is that it could break a lot of old sites. In some older versions of BigTree, the external link field data would stick around but the template would change from empty (for external links) to whatever the user chooses.

The BigTree router checks for the presence of the empty template before a redirect can happen due to that historical reason. If we preserved the template information we'd have to store it in a different column rather than "template" or we'd either run into real redirects not working (because it still sees the template) or fake redirects happening because we check the "external" column and prioritize it over the template.

You should be able to restore the latest page revision through the Revisions tab (as long as the user is a publisher) when editing a page (and that should pop the template and its data back out). Is that not working for your workflow? If not I can think on this some more.
