### ISSUE TITLE
View images uploaded through module

### ISSUE THREAD

**Issue by doonmok** [bigtreecms/BigTree-CMS#340]
When uploading an image through a module, there is the Upload or Browse buttons. The browse you can see what images there are but cannot see the images that were uploaded through the Upload button. 

Is there a way to view the images that were uploaded through the upload button through BigTree or the database?

**Comment by timbuckingham** [comment]
Content uploaded through regular upload fields (and not the file manager) is treated as unmanaged content and isn't tracked anywhere. The same is true if you select an image from the file manager when using an upload field (an unmanaged copy is made and modified for that individual field).

BigTree 4.3 is introducing an updated file manager alongside an Image Reference field which allows you to tie a image field directly to content in the file browser (so that when the referenced image is updated your field has the latest copy at all times).

**Comment by doonmok** [comment]
Thanks Tim
