### ISSUE TITLE
301 vs 302 redirects

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#351]
I'd like to suggest a patch in ⁨core⁩/⁨inc/bigtree⁩/utils.php on line 1882 to change 

`static function redirect($url = false, $codes = array("302")) {`

to

`static function redirect($url = false, $codes = array("301")) {`

This would ensure that PageRank and other SEO transfers to redirected pages by using a permanent redirect instead of a temporary redirect.

https://en.ryte.com/wiki/Redirect

**Comment by timbuckingham** [comment]
BigTree passes a proper 301 when handling 404 redirects (through BigTreeCMS::handle404).
Generally when BigTree::redirect is being called (from the back-end) it's when a page is processing something and then redirecting elsewhere (e.g. creating crops, redirecting back to the list view) which I think 302 "found" is the right code for.

Is there somewhere BigTree's incorrectly passing 302s when it should use a permanent redirect?

**Comment by mbriney** [comment]
We are seeing it happening throughout our entire site.  It's something we flagged for Katie.  When I manually edited the file it resolved and everything moved to a proper 301.

**Comment by timbuckingham** [comment]
Can you point me to a URL you're experiencing this at? I checked https://www.mountvernon.org/petition/ via cURL and properly got a 301:

Tims-MacBook-Pro:~ timb$ curl -i "https://www.mountvernon.org/petition"
HTTP/1.1 301 Moved Permanently
Date: Mon, 05 Nov 2018 19:38:45 GMT
Server: Apache/2.4.34 (IUS) OpenSSL/1.0.1e-fips
X-Powered-By: PHP/7.1.23
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=b07ccc36c30475fa3b58f9b62389c796; path=/; HttpOnly
Location: https://www.mountvernon.org/preservation/viewshed/sign-the-petition/
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: master-only
Content-Length: 0
Content-Type: text/html;charset=UTF-8

**Comment by mbriney** [comment]
Yes, here are two examples:

curl -i https://www.mountvernon.org/videos-2/
HTTP/1.1 302 Found
Date: Tue, 06 Nov 2018 13:03:14 GMT
Server: Apache/2.4.34 (IUS) OpenSSL/1.0.1e-fips
X-Powered-By: PHP/7.1.23
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=3672665908f8b1b01fa578f2d246e4ad; path=/; HttpOnly
Location: https://www.mountvernon.org/video
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: master-only
Content-Length: 0
Content-Type: text/html;charset=UTF-8


curl -i https://www.mountvernon.org/plan-your-visit/calendar
HTTP/1.1 302 Found
Date: Tue, 06 Nov 2018 13:04:11 GMT
Server: Apache/2.4.34 (IUS) OpenSSL/1.0.1e-fips
X-Powered-By: PHP/7.1.23
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=38e45478617c77fa0a482f517774cf79; path=/; HttpOnly
Location: https://www.mountvernon.org/plan-your-visit/calendar/2018-11-06/
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: master-only
Content-Length: 0
Content-Type: text/html;charset=UTF-8

**Comment by timbuckingham** [comment]
Matt,

I looked into this some more and there are definitely some that are bad redirects that will be addressed but I'm not sure of others.

Your first example appears to be a page that's linking to another page using the external link field. Really that should be a 301 redirect using the 404 manager. I think a 302 for an external link based page is the right call because browsers cache 301 redirects (because they're permanent). You'd lose the ability to reliably edit that URL in Pages if it passed a 301.

I think your second example is the template calling BigTree::redirect without a parameter passed. It should likely be passing a 301 parameter after the redirect URL. Again, I don't think defaulting BigTree::redirect to a 301 is a good idea because everywhere it's used for redirecting after the admin or a template processes user input would now be cached and potentially miss the processing page due to browsers auto-redirecting.

I did find that the router is passing 302 redirects for when you hit a page on a multi-site environment that should be on a different domain -- that should definitely be a 301!

Regarding PageRank and 301/302/303/307 responses, it looks like Google now considers them all the same:
https://moz.com/blog/301-redirection-rules-for-seo

Let me know your thoughts!
