### ISSUE TITLE
Cron does not work. Config is not found

### ISSUE THREAD

**Issue by ddrozdik** [bigtreecms/BigTree-CMS#361]
Hi,

After implementing the fix for the sitemap.xml(https://github.com/bigtreecms/BigTree-CMS/pull/360) we discovered that we can't execute cron according to documentation https://www.bigtreecms.org/developers/dev-guide/advanced/cron-daily-digest

After adding configuration to crontab 
```
php -f /var/www/dev/htdocs/core/cron.php
```
 we get an error
```
PHP Warning:  include(/var/www/dev/htdocs/bigtree/custom/environment.php): failed to open stream: No such file or directory in /var/www/dev/htdocs/bigtree/core/cron.php on line 3
PHP Warning:  include(): Failed opening '/var/www/dev/htdocs/bigtree/custom/environment.php' for inclusion (include_path='.:/opt/remi/php71/root/usr/share/pear:/opt/remi/php71/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/dev/htdocs/bigtree/core/cron.php on line 3
PHP Warning:  include(/var/www/dev/htdocs/bigtree/custom/settings.php): failed to open stream: No such file or directory in /var/www/dev/htdocs/bigtree/core/cron.php on line 4
PHP Warning:  include(): Failed opening '/var/www/dev/htdocs/bigtree/custom/settings.php' for inclusion (include_path='.:/opt/remi/php71/root/usr/share/pear:/opt/remi/php71/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/dev/htdocs/bigtree/core/cron.php on line 4
```
And this is actually related to the code from the `cron.php` file https://github.com/bigtreecms/BigTree-CMS/blob/4.4-devel/core/cron.php#L3
```php
	$server_root = str_replace("core/cron.php","",strtr(__FILE__, "\\", "/"));
	include $server_root."custom/environment.php";
	include $server_root."custom/settings.php";
	include $server_root."core/bootstrap.php";
	include $server_root."core/inc/bigtree/sitemap.php";
```
`custom` folder is always located outside of `bigtree` but the code does not count on this and is trying to find needed file inside of `bigtree` folder. 

I would mark this as an important thing to fix asap. 

cc @timbuckingham

**Comment by ddrozdik** [comment]
Hi @timbuckingham, Do you have any thoughts on how to fix it quickly?

**Comment by timbuckingham** [comment]
Hi,

Am I understanding correctly that /bigtree/ is the git repository of BigTree and you're sym-linking /bigtree/core/ to /core/? (We do this frequently to allow quick git pull upgrades of BigTree).

If so, this is actually due to some environments improperly registering the symlink location in __FILE__ so it's reported as /bigtree/core/cron.php rather than /core/cron.php. I'm not entirely sure what the best way to resolve that is since "bigtree" is an arbitrary name for the submodule folder.

I'm open to ideas! I guess in theory we could do something like go up one directory if file_exists for $server_root."custom/settings.php" fails and try to set $server_root to there. Thoughts?

**Comment by ddrozdik** [comment]
@timbuckingham please take a look on https://github.com/bigtreecms/BigTree-CMS/pull/362

**Comment by timbuckingham** [comment]
I just pushed up a commit that on upgrade will create a "cron-run.php" script in the root directory of the site that should resolve issues with symlinked core paths. You'll need to instead use cron-run.php rather than /core/cron.php in your cron scripts, but it should resolve the issue!
